name: face_camera
description: A Flutter camera plugin that detects faces in real-time. In addition it can capture automatically once a face is detected, This can be handy while taking a selfie during kyc.
version: 0.1.4
homepage: https://github.com/Conezi/face_camera

environment:
  sdk: ">=3.8.0 <=4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3
  google_mlkit_face_detection: ^0.13.1
  flutter_plugin_android_lifecycle: ^2.0.32
  camera_android_camerax: ^0.6.24

dependency_overrides:
  camera_platform_interface: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  plugin:
    platforms:
      android:
        package: com.conezi.face_camera
        pluginClass: FaceCameraPlugin
      ios:
        pluginClass: FaceCameraPlugin